### ISSUE TITLE
Possible i18n support?

### ISSUE THREAD

**Issue by MingcongBai** [gnunn1/vgrep#1]
As a useful tool (and a GNOME HIG- compliant tool is a even better tool), I would love to package this for the distribution I am currently maintaining...

While it looks all very good right now, would there be any plan for i18n work ahead to add the extra bling to the project?

Best Regards,
Mingcong (Jeff) Bai

**Comment by gnunn1** [comment]
Sure, now that I've done it in Terminix I can port the same here. This app also needs to be re-compiled with the newest version of GtkD to fix a memory issue so I'll do that at the same time and cut a new release. Give me a week or two to get to it as I need to work on some Terminix items first.

**Comment by MingcongBai** [comment]
Awesome! I will be more than happy to help with some L10n work mate.
2016年2月22日 16:36，"Gerald Nunn" notifications@github.com写道：

**Comment by MingcongBai** [comment]
Guess I can close this for now.
