### ISSUE TITLE
How to install this under Ubuntu 18.04? 

### ISSUE THREAD

**Issue by roboirc** [gnunn1/vgrep#5]
Dear gnunn1 
How do we install it and run it under Ubuntu 18.04? Can you give me the steps because README.md in the repository is not clear. Which additional debian packages are needed? 
Thanks

**Comment by gnunn1** [comment]
I'm not supporting this application any longer, I'd recommend looking for an alternative. I'll update the readme to say so.

**Comment by roboirc** [comment]
Can you recommend an alternative similar to your application at least? 
I found a few including Search Monkey (but it crashes often). Thanks!

**Comment by gnunn1** [comment]
I do not, sorry.
